import { AppState } from './types';

export const initialMockState: AppState = {
  mode: 'elder',
  profile: {
    name: 'Grandma Lakshmi Devi',
    age: 72,
    location: 'Guwahati, Assam',
    language: 'en',
    voiceAssistance: true,
    reminderAssistance: true,
    onboarded: true,
  },
  streakCount: 5,
  streakHistory: [
    { day: 'Mon', completed: true },
    { day: 'Tue', completed: true },
    { day: 'Wed', completed: true },
    { day: 'Thu', completed: true },
    { day: 'Fri', completed: true },
    { day: 'Sat', completed: false },
    { day: 'Sun', completed: false },
  ],
  wishCardUnlocked: false,
  wishCardContent: '',
  gardenPlants: [
    {
      id: 'p1',
      name: 'Tulsi Blossom',
      stage: 'flower',
      plantedDate: '2026-08-20',
      memory: 'Planted after remembering my mother’s morning tea recipe.',
      icon: '🌿',
      health: 100,
    },
    {
      id: 'p2',
      name: 'Sunshine Marigold',
      stage: 'mature',
      plantedDate: '2026-08-17',
      memory: 'Celebrated 3-day streak with daughter Priya on phone.',
      icon: '🌼',
      health: 95,
    },
    {
      id: 'p3',
      name: 'Little Jasmine Sprout',
      stage: 'sprout',
      plantedDate: '2026-08-23',
      memory: 'Completed memory match game effortlessly.',
      icon: '🌱',
      health: 90,
    },
  ],
  reminders: [
    {
      id: 'r1',
      title: 'Morning Blood Pressure & Vitamin D',
      time: '08:30 AM',
      type: 'medicine',
      completedToday: true,
      icon: '💊',
      notes: 'Take with half glass of warm water.',
    },
    {
      id: 'r2',
      title: 'Fresh Coconut Water & Hydration',
      time: '11:00 AM',
      type: 'hydration',
      completedToday: false,
      icon: '🥥',
      notes: 'Keep refreshed during afternoon warm weather.',
    },
    {
      id: 'r3',
      title: 'Afternoon Cardamom Tea & Biscuits',
      time: '04:00 PM',
      type: 'meal',
      completedToday: false,
      icon: '🫖',
      notes: 'Enjoy with family members.',
    },
    {
      id: 'r4',
      title: 'Evening Relaxing Walk in Verandah',
      time: '05:30 PM',
      type: 'activity',
      completedToday: false,
      icon: '🚶‍♀️',
      notes: '15 minutes gentle stroll.',
    },
  ],
  connectionQuest: {
    id: 'cq-1',
    task: 'Call your son or daughter today and tell them one thing that made you smile.',
    completed: false,
    emotionalResponse: undefined,
  },
  memories: [
    {
      id: 'm1',
      date: 'August 23, 2026',
      type: 'family',
      content: 'Today I spoke with my daughter Priya. She told me about her garden flowers.',
    },
    {
      id: 'm2',
      date: 'August 21, 2026',
      type: 'thought',
      content: 'Remembered the sweet smell of wet soil after monsoon rain in Assam.',
    },
    {
      id: 'm3',
      date: 'August 19, 2026',
      type: 'wish',
      content: 'Wish to cook special payogesh for family gathering this weekend.',
    },
  ],
  gameHistory: [
    {
      gameId: 'memory-match',
      gameName: 'Memory Match',
      score: 5,
      maxScore: 5,
      difficulty: 'comfortable',
      timestamp: '2026-08-23 10:15 AM',
      timeSpentSeconds: 145,
    },
    {
      gameId: 'object-recognition',
      gameName: 'Object Recognition',
      score: 4,
      maxScore: 5,
      difficulty: 'comfortable',
      timestamp: '2026-08-22 11:30 AM',
      timeSpentSeconds: 120,
    },
    {
      gameId: 'pattern-recognition',
      gameName: 'Pattern Recognition',
      score: 3,
      maxScore: 4,
      difficulty: 'gentle',
      timestamp: '2026-08-21 09:45 AM',
      timeSpentSeconds: 180,
    },
  ],
  alerts: [
    {
      id: 'a1',
      timestamp: 'Today, 09:00 AM',
      level: 'info',
      message: 'Morning medicine successfully confirmed by Grandma Lakshmi.',
      acknowledged: true,
    },
    {
      id: 'a2',
      timestamp: 'Yesterday, 06:15 PM',
      level: 'warning',
      message: 'Afternoon hydration reminder pending completion.',
      acknowledged: false,
    },
  ],
  isVoiceActive: false,
  offlineMode: false,
  syncStatus: 'synced',
  difficultyLevel: 'comfortable',
};
